name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: can-npm-publish
        run: npx can-npm-publish --verbose
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: release
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
